site_name: MkDocs example
site_description: 'A MkDocs example'
site_author: 'Chris (but actually Michael Hausenblas)'
docs_dir: docs/
repo_name: 'k-cybulski/mkdocs-example'
repo_url: 'https://github.com/k-cybulski/mkdocs-example'
nav:
    - Home: index.md
theme:
  name: 'readthedocs'
